"""Countries table added

Revision ID: f05bbb82fe45
Revises: 367c5c3a0c05
Create Date: 2019-07-19 10:44:36.201710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05bbb82fe45'
down_revision = '367c5c3a0c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alpha_2', sa.String(), nullable=True),
    sa.Column('alpha_3', sa.String(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
